apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: soben-out9150-react
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/soben-out9150-react.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: soben-out9150-react
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
