apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: soben-out9150-react-certificate
  namespace: soben-out9150-react
spec:
  secretName: soben-out9150-react-secret-tls
  commonName: soben-out9150-react.assessify.org
  dnsNames:
  - soben-out9150-react.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
