apiVersion: v1
kind: Service
metadata:
  name: soben-out9150-react-service
spec:
  type: NodePort
  selector:
    app: soben-out9150-react
  ports:
    - protocol: TCP
      port: 8288
      targetPort: 3000
